In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv("../data/Atlantic_Spain.csv")

df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 27800
Columns: 10

In [5]:
print("Columns in the dataset:")
for column in df.columns:
    print("-", column)

Columns in the dataset:
- date
- position
- song
- artist
- popularity
- duration_ms
- album_type
- total_tracks
- is_explicit
- album_cover_url

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  str
 1   position         27800 non-null  int64
 2   song             27800 non-null  str
 3   artist           27800 non-null  str
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  str
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  str
dtypes: bool(1), int64(4), str(5)
memory usage: 4.8 MB

In [7]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

In [8]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("\nMissing percentage:")
print(missing_percentage)

Missing percentage:
date               0.0
position           0.0
song               0.0
artist             0.0
popularity         0.0
duration_ms        0.0
album_type         0.0
total_tracks       0.0
is_explicit        0.0
album_cover_url    0.0
dtype: float64

In [9]:
duplicate_rows = df.duplicated().sum()

print("Total duplicate rows:", duplicate_rows)

Total duplicate rows: 15

In [10]:
if duplicate_rows == 0:
    print("No duplicate rows found.")
else:
    print("Duplicate rows found. We will investigate them before removing anything.")

Duplicate rows found. We will investigate them before removing anything.

In [11]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["date", "position", "song"]
)

duplicates

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14401,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14402,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14403,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14404,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14405,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14406,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14408,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14411,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14416,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14418,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14419,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14434,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14438,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14439,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...
14449,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...

In [12]:
print("Number of duplicate records displayed:", len(duplicates))

Number of duplicate records displayed: 30

In [13]:
duplicate_check = df[df.duplicated(keep=False)]

print("Total duplicate rows:", len(duplicate_check))
print("Unique duplicated records:", duplicate_check.drop_duplicates().shape[0])

Total duplicate rows: 30
Unique duplicated records: 15

In [14]:
duplicate_check.drop_duplicates()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...

In [15]:
daily_counts = df.groupby("date").size()

print("Number of unique dates:", len(daily_counts))
print("\nDaily record count summary:")
print(daily_counts.describe())

Number of unique dates: 555

Daily record count summary:
count    555.000000
mean      50.090090
std        2.122382
min       50.000000
25%       50.000000
50%       50.000000
75%       50.000000
max      100.000000
dtype: float64

In [16]:
print("Dates with exactly 50 records:",
      (daily_counts == 50).sum())

print("Dates with records other than 50:",
      (daily_counts != 50).sum())

Dates with exactly 50 records: 554
Dates with records other than 50: 1

In [17]:
print("\nDates that do NOT have exactly 50 records:")
print(daily_counts[daily_counts != 50])

Dates that do NOT have exactly 50 records:
date
01-03-2025    100
dtype: int64

In [18]:
abnormal_date = df[df["date"] == "01-03-2025"]

print("Records on 01-03-2025:", len(abnormal_date))
print("\nPosition counts:")
print(abnormal_date["position"].value_counts().sort_index())

Records on 01-03-2025: 100

Position counts:
position
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    2
33    2
34    2
35    2
36    2
37    2
38    2
39    2
40    2
41    2
42    2
43    2
44    2
45    2
46    2
47    2
48    2
49    2
50    2
Name: count, dtype: int64

In [19]:
abnormal_date.sort_values("position")

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...
14400,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,79,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...
14401,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14402,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14403,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14404,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14405,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14406,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14407,01-03-2025,8,Casanova,Soolking & Lola Indigo & Rvfv,82,243806,single,1,False,https://i.scdn.co/image/ab67616d0000b2732adf05...
14357,01-03-2025,8,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,187172,single,1,False,https://i.scdn.co/image/ab67616d0000b2737b5840...
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14408,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14409,01-03-2025,10,Gata Only,FloyyMenor & Cris Mj,90,222000,single,1,True,https://i.scdn.co/image/ab67616d0000b2731d0777...
14359,01-03-2025,10,Casanova,Soolking & Lola Indigo & Rvfv,83,243806,single,1,False,https://i.scdn.co/image/ab67616d0000b2732adf05...
14360,01-03-2025,11,Gata Only,FloyyMenor & Cris Mj,90,222000,single,1,True,https://i.scdn.co/image/ab67616d0000b2731d0777...
14410,01-03-2025,11,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,187172,single,1,False,https://i.scdn.co/image/ab67616d0000b2737b5840...
14411,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14362,01-03-2025,13,La_Original.mp3,Emilia,85,140625,album,13,False,https://i.scdn.co/image/ab67616d0000b273bfb945...
14412,01-03-2025,13,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,232645,single,1,False,https://i.scdn.co/image/ab67616d0000b273531164...
14413,01-03-2025,14,La_Original.mp3,Emilia,85,140625,album,13,False,https://i.scdn.co/image/ab67616d0000b273bfb945...
14363,01-03-2025,14,LA ÚLTIMA,Quevedo,84,170322,single,1,False,https://i.scdn.co/image/ab67616d0000b27366a722...
14364,01-03-2025,15,PERRO NEGRO,Bad Bunny,95,162767,album,22,True,https://i.scdn.co/image/ab67616d0000b2737b1fc5...
14414,01-03-2025,15,LA ÚLTIMA,Quevedo,83,170322,single,1,False,https://i.scdn.co/image/ab67616d0000b27366a722...
14415,01-03-2025,16,PERRO NEGRO,Bad Bunny,95,162767,album,22,True,https://i.scdn.co/image/ab67616d0000b2737b1fc5...
14365,01-03-2025,16,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,232645,single,1,False,https://i.scdn.co/image/ab67616d0000b273531164...
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14416,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14417,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,61,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...
14367,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,60,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14418,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14419,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14370,01-03-2025,21,Columbia,Quevedo,92,186000,single,1,False,https://i.scdn.co/image/ab67616d0000b273a00a81...
14420,01-03-2025,21,LA CAPI,Myke Towers,80,202360,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14421,01-03-2025,22,Columbia,Quevedo,91,186000,single,1,False,https://i.scdn.co/image/ab67616d0000b273a00a81...
14371,01-03-2025,22,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,235146,single,1,True,https://i.scdn.co/image/ab67616d0000b2734e3fa2...
14372,01-03-2025,23,MODELITO,Mora,83,190496,album,14,True,https://i.scdn.co/image/ab67616d0000b273076ef0...
14422,01-03-2025,23,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,235146,single,1,True,https://i.scdn.co/image/ab67616d0000b2734e3fa2...
14423,01-03-2025,24,MODELITO,Mora,83,190496,album,14,True,https://i.scdn.co/image/ab67616d0000b273076ef0...
14373,01-03-2025,24,LA CAPI,Myke Towers,80,202360,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14374,01-03-2025,25,REINA,Mora,84,211879,album,15,True,https://i.scdn.co/image/ab67616d0000b2734cc96e...
14424,01-03-2025,25,EMPELOTICA,Lenny Tavárez & Feid,78,190322,single,1,True,https://i.scdn.co/image/ab67616d0000b2732733f7...
14425,01-03-2025,26,REINA,Mora,84,211879,album,15,True,https://i.scdn.co/image/ab67616d0000b2734cc96e...
14375,01-03-2025,26,DILUVIO,Rauw Alejandro,90,197052,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...
14376,01-03-2025,27,COSAS QUE NO TE DIJE,Saiko,84,224725,single,1,False,https://i.scdn.co/image/ab67616d0000b273fb045f...
14426,01-03-2025,27,Hey Lil Mama,Eladio Carrion,85,216338,album,17,False,https://i.scdn.co/image/ab67616d0000b273ec105e...
14427,01-03-2025,28,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,173991,single,1,True,https://i.scdn.co/image/ab67616d0000b2735b8ec2...
14377,01-03-2025,28,QLONA,KAROL G,93,172797,album,9,True,https://i.scdn.co/image/ab67616d0000b273d026bf...
14378,01-03-2025,29,EMPELOTICA,Lenny Tavárez & Feid,77,190322,single,1,True,https://i.scdn.co/image/ab67616d0000b2732733f7...
14428,01-03-2025,29,DILUVIO,Rauw Alejandro,90,197052,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...
14429,01-03-2025,30,COSAS QUE NO TE DIJE,Saiko,84,224725,single,1,False,https://i.scdn.co/image/ab67616d0000b273fb045f...
14379,01-03-2025,30,Hey Lil Mama,Eladio Carrion,86,216338,album,17,False,https://i.scdn.co/image/ab67616d0000b273ec105e...
14380,01-03-2025,31,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,173991,single,1,True,https://i.scdn.co/image/ab67616d0000b2735b8ec2...
14430,01-03-2025,31,Madrid City,Ana Mena,79,172727,single,1,False,https://i.scdn.co/image/ab67616d0000b2739c3dc8...
14431,01-03-2025,32,OA,Anuel AA & Quevedo & Maluma,86,235200,single,1,True,https://i.scdn.co/image/ab67616d0000b27331e30d...
14381,01-03-2025,32,Madrid City,Ana Mena,79,172727,single,1,False,https://i.scdn.co/image/ab67616d0000b2739c3dc8...
14432,01-03-2025,33,QLONA,KAROL G,93,172797,album,9,True,https://i.scdn.co/image/ab67616d0000b273d026bf...
14382,01-03-2025,33,BABY HELLO,Rauw Alejandro,78,222461,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...
14383,01-03-2025,34,OA,Anuel AA & Quevedo & Maluma,86,235200,single,1,True,https://i.scdn.co/image/ab67616d0000b27331e30d...
14433,01-03-2025,34,BABY HELLO,Rauw Alejandro,77,222461,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...
14434,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14385,01-03-2025,36,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,248004,single,1,False,https://i.scdn.co/image/ab67616d0000b273dd62eb...
14435,01-03-2025,36,La Bachata,Manuel Turizo,86,162637,album,15,False,https://i.scdn.co/image/ab67616d0000b2734dd995...
14436,01-03-2025,37,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,248004,single,1,False,https://i.scdn.co/image/ab67616d0000b273dd62eb...
14386,01-03-2025,37,La Bachata,Manuel Turizo,87,162637,album,15,False,https://i.scdn.co/image/ab67616d0000b2734dd995...
14387,01-03-2025,38,LALA,Myke Towers,92,197920,album,23,True,https://i.scdn.co/image/ab67616d0000b2730656d5...
14437,01-03-2025,38,Quien Es Dei V?,Dei V,81,162244,single,1,True,https://i.scdn.co/image/ab67616d0000b27348093f...
14438,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14439,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14440,01-03-2025,41,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,172095,single,1,False,https://i.scdn.co/image/ab67616d0000b2733d2a29...
14390,01-03-2025,41,Quien Es Dei V?,Dei V,81,162244,single,1,True,https://i.scdn.co/image/ab67616d0000b27348093f...
14391,01-03-2025,42,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,172095,single,1,False,https://i.scdn.co/image/ab67616d0000b2733d2a29...
14441,01-03-2025,42,LALA,Myke Towers,92,197920,album,23,True,https://i.scdn.co/image/ab67616d0000b2730656d5...
14442,01-03-2025,43,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,215600,single,1,False,https://i.scdn.co/image/ab67616d0000b2732d6016...
14392,01-03-2025,43,lady madrizZz,céro,75,131020,single,1,False,https://i.scdn.co/image/ab67616d0000b2736eb7f1...
14393,01-03-2025,44,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,215600,single,1,False,https://i.scdn.co/image/ab67616d0000b2732d6016...
14443,01-03-2025,44,lady madrizZz,céro,75,131020,single,1,False,https://i.scdn.co/image/ab67616d0000b2736eb7f1...
14444,01-03-2025,45,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,191320,single,1,True,https://i.scdn.co/image/ab67616d0000b27306eccb...
14394,01-03-2025,45,Holanda,Jhayco,86,231693,single,1,True,https://i.scdn.co/image/ab67616d0000b273cd2ceb...
14395,01-03-2025,46,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,191320,single,1,True,https://i.scdn.co/image/ab67616d0000b27306eccb...
14445,01-03-2025,46,PERREO LENTO,Chris Jedi & Gaby Music & Dei V,73,156640,single,5,True,https://i.scdn.co/image/ab67616d0000b273a65227...
14446,01-03-2025,47,Holanda,Jhayco,86,231693,single,1,True,https://i.scdn.co/image/ab67616d0000b273cd2ceb...
14396,01-03-2025,47,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...
14397,01-03-2025,48,El Mambo,Kiko Rivera,76,129845,single,1,False,https://i.scdn.co/image/ab67616d0000b2739550e7...
14447,01-03-2025,48,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...
14448,01-03-2025,49,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...
14398,01-03-2025,49,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...
14449,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...

In [20]:
print(abnormal_date["position"].value_counts().sort_index())

position
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    2
33    2
34    2
35    2
36    2
37    2
38    2
39    2
40    2
41    2
42    2
43    2
44    2
45    2
46    2
47    2
48    2
49    2
50    2
Name: count, dtype: int64

In [21]:
print("Unique songs:", abnormal_date["song"].nunique())
print("Total records:", len(abnormal_date))

Unique songs: 51
Total records: 100

In [22]:
position_counts = abnormal_date["position"].value_counts().sort_index()

print(position_counts)

position
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    2
33    2
34    2
35    2
36    2
37    2
38    2
39    2
40    2
41    2
42    2
43    2
44    2
45    2
46    2
47    2
48    2
49    2
50    2
Name: count, dtype: int64

In [23]:
print("Positions occurring twice:")
print(position_counts[position_counts == 2].index.tolist())

print("\nPositions occurring once:")
print(position_counts[position_counts == 1].index.tolist())

Positions occurring twice:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

Positions occurring once:
[]

In [24]:
duplicate_locations = (
    df[df.duplicated(keep=False)]
    .groupby("date")
    .size()
    .sort_values(ascending=False)
)

print("Duplicate records by date:")
print(duplicate_locations)

Duplicate records by date:
date
01-03-2025    30
dtype: int64

In [25]:
print("Number of dates containing duplicates:", len(duplicate_locations))

Number of dates containing duplicates: 1

In [26]:
duplicate_dates = df[df.duplicated(keep=False)]["date"].unique()

print("Dates containing duplicate records:")
for d in duplicate_dates:
    print(d)

Dates containing duplicate records:
01-03-2025

In [27]:
march_1 = df[df["date"] == "01-03-2025"].copy()

march_1_sorted = march_1.sort_values(
    by=["position", "song", "artist"]
)

march_1_sorted[
    ["position", "song", "artist", "popularity", "album_type", "is_explicit"]
]

,position,song,artist,popularity,album_type,is_explicit
14350,1,FARDOS,JC Reyes & De La Ghetto,78,single,False
14400,1,FARDOS,JC Reyes & De La Ghetto,79,single,False
14351,2,Manos Rotas,DELLAFUENTE & Morad,85,single,False
14401,2,Manos Rotas,DELLAFUENTE & Morad,85,single,False
14352,3,LA FALDA,Myke Towers,94,album,True
14402,3,LA FALDA,Myke Towers,94,album,True
14353,4,X'CLUSIVO,Gonzy,81,single,True
14403,4,X'CLUSIVO,Gonzy,81,single,True
14354,5,LUNA,Feid,97,album,False
14404,5,LUNA,Feid,97,album,False
14355,6,M.A.I,Milo j,89,album,False
14405,6,M.A.I,Milo j,89,album,False
14356,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,single,False
14406,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,single,False
14407,8,Casanova,Soolking & Lola Indigo & Rvfv,82,single,False
14357,8,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,single,False
14358,9,Mamichula - con Nicki Nicole,Trueno,88,album,False
14408,9,Mamichula - con Nicki Nicole,Trueno,88,album,False
14359,10,Casanova,Soolking & Lola Indigo & Rvfv,83,single,False
14409,10,Gata Only,FloyyMenor & Cris Mj,90,single,True
14360,11,Gata Only,FloyyMenor & Cris Mj,90,single,True
14410,11,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,single,False
14361,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,single,False
14411,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,single,False
14412,13,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,single,False
14362,13,La_Original.mp3,Emilia,85,album,False
14363,14,LA ÚLTIMA,Quevedo,84,single,False
14413,14,La_Original.mp3,Emilia,85,album,False
14414,15,LA ÚLTIMA,Quevedo,83,single,False
14364,15,PERRO NEGRO,Bad Bunny,95,album,True
14365,16,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,single,False
14415,16,PERRO NEGRO,Bad Bunny,95,album,True
14366,17,UNA BACHATA,Lola Indigo,77,album,False
14416,17,UNA BACHATA,Lola Indigo,77,album,False
14367,18,Buscando Money,TWENTY SIX & Tayson Kryss,60,single,False
14417,18,Buscando Money,TWENTY SIX & Tayson Kryss,61,single,False
14368,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,single,False
14418,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,single,False
14369,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,single,False
14419,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,single,False
14370,21,Columbia,Quevedo,92,single,False
14420,21,LA CAPI,Myke Towers,80,album,True
14371,22,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,single,True
14421,22,Columbia,Quevedo,91,single,False
14422,23,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,single,True
14372,23,MODELITO,Mora,83,album,True
14373,24,LA CAPI,Myke Towers,80,album,True
14423,24,MODELITO,Mora,83,album,True
14424,25,EMPELOTICA,Lenny Tavárez & Feid,78,single,True
14374,25,REINA,Mora,84,album,True
14375,26,DILUVIO,Rauw Alejandro,90,album,True
14425,26,REINA,Mora,84,album,True
14376,27,COSAS QUE NO TE DIJE,Saiko,84,single,False
14426,27,Hey Lil Mama,Eladio Carrion,85,album,False
14427,28,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,single,True
14377,28,QLONA,KAROL G,93,album,True
14428,29,DILUVIO,Rauw Alejandro,90,album,True
14378,29,EMPELOTICA,Lenny Tavárez & Feid,77,single,True
14429,30,COSAS QUE NO TE DIJE,Saiko,84,single,False
14379,30,Hey Lil Mama,Eladio Carrion,86,album,False
14430,31,Madrid City,Ana Mena,79,single,False
14380,31,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,single,True
14381,32,Madrid City,Ana Mena,79,single,False
14431,32,OA,Anuel AA & Quevedo & Maluma,86,single,True
14382,33,BABY HELLO,Rauw Alejandro,78,album,True
14432,33,QLONA,KAROL G,93,album,True
14433,34,BABY HELLO,Rauw Alejandro,77,album,True
14383,34,OA,Anuel AA & Quevedo & Maluma,86,single,True
14384,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,single,True
14434,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,single,True
14385,36,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,single,False
14435,36,La Bachata,Manuel Turizo,86,album,False
14436,37,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,single,False
14386,37,La Bachata,Manuel Turizo,87,album,False
14387,38,LALA,Myke Towers,92,album,True
14437,38,Quien Es Dei V?,Dei V,81,single,True
14388,39,Si No Estás,iñigo quintero,93,single,False
14438,39,Si No Estás,iñigo quintero,93,single,False
14389,40,Buenas,Quevedo & Saiko,80,single,False
14439,40,Buenas,Quevedo & Saiko,80,single,False
14440,41,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,single,False
14390,41,Quien Es Dei V?,Dei V,81,single,True
14391,42,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,single,False
14441,42,LALA,Myke Towers,92,album,True
14442,43,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,single,False
14392,43,lady madrizZz,céro,75,single,False
14393,44,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,single,False
14443,44,lady madrizZz,céro,75,single,False
14444,45,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,single,True
14394,45,Holanda,Jhayco,86,single,True
14395,46,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,single,True
14445,46,PERREO LENTO,Chris Jedi & Gaby Music & Dei V,73,single,True
14446,47,Holanda,Jhayco,86,single,True
14396,47,NO PIENSO LLAMAR,Soge Culebra,70,album,False
14397,48,El Mambo,Kiko Rivera,76,single,False
14447,48,Tacos Gucci,Anuel AA,84,single,True
14448,49,NO PIENSO LLAMAR,Soge Culebra,70,album,False
14398,49,Tacos Gucci,Anuel AA,84,single,True
14399,50,TU$$I (with Dei V),YOVNGCHIMI,76,album,True
14449,50,TU$$I (with Dei V),YOVNGCHIMI,76,album,True

In [28]:
march_1.groupby("position").agg(
    records=("song", "size"),
    unique_songs=("song", "nunique")
).head(50)

          records  unique_songs
position
1               2             1
2               2             1
3               2             1
4               2             1
5               2             1
6               2             1
7               2             1
8               2             2
9               2             1
10              2             2
11              2             2
12              2             1
13              2             2
14              2             2
15              2             2
16              2             2
17              2             1
18              2             1
19              2             1
20              2             1
21              2             2
22              2             2
23              2             2
24              2             2
25              2             2
26              2             2
27              2             2
28              2             2
29              2             2
30              2             2
31              2             2
32              2             2
33              2             2
34              2             2
35              2             1
36              2             2
37              2             2
38              2             2
39              2             1
40              2             1
41              2             2
42              2             2
43              2             2
44              2             2
45              2             2
46              2             2
47              2             2
48              2             2
49              2             2
50              2             1

In [29]:
march_1[march_1.duplicated(
    subset=["position", "song", "artist"],
    keep=False
)].sort_values("position")

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...
14400,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,79,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...
14401,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14402,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...
14403,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14404,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...
14405,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14406,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...
14408,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...
14411,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14416,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...
14417,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,61,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...
14367,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,60,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14418,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...
14419,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14434,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...
14438,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14439,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...
14449,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...

In [30]:
duplicate_same_position = march_1.duplicated(
    subset=["position", "song", "artist"],
    keep=False
).sum()

print("Duplicate records with same position + song + artist:",
      duplicate_same_position)

Duplicate records with same position + song + artist: 34

In [31]:
position_song_counts = (
    march_1.groupby("position")["song"]
    .nunique()
)

print("Positions with 1 unique song:",
      (position_song_counts == 1).sum())

print("Positions with 2 unique songs:",
      (position_song_counts == 2).sum())

Positions with 1 unique song: 17
Positions with 2 unique songs: 33

In [32]:
march_1_summary = (
    march_1.groupby("position")
    .agg(
        songs=("song", list),
        popularity=("popularity", list)
    )
)

march_1_summary.head(10)

                                                      songs popularity
position
1                                          [FARDOS, FARDOS]   [78, 79]
2                                [Manos Rotas, Manos Rotas]   [85, 85]
3                                      [LA FALDA, LA FALDA]   [94, 94]
4                                    [X'CLUSIVO, X'CLUSIVO]   [81, 81]
5                                              [LUNA, LUNA]   [97, 97]
6                                            [M.A.I, M.A.I]   [89, 89]
7         [Una Foto Remix (feat. Emilia), Una Foto Remix...   [92, 92]
8         [Young Miko: Bzrp Music Sessions, Vol. 58, Cas...   [94, 82]
9         [Mamichula - con Nicki Nicole, Mamichula - con...   [88, 88]
10                                    [Casanova, Gata Only]   [83, 90]

In [33]:
march_1_summary.loc[1:5]

                               songs popularity
position
1                   [FARDOS, FARDOS]   [78, 79]
2         [Manos Rotas, Manos Rotas]   [85, 85]
3               [LA FALDA, LA FALDA]   [94, 94]
4             [X'CLUSIVO, X'CLUSIVO]   [81, 81]
5                       [LUNA, LUNA]   [97, 97]

In [34]:
different_positions = (
    march_1.groupby("position")["song"]
    .nunique()
)

different_positions = different_positions[
    different_positions == 2
]

print("Positions containing two different songs:")
print(different_positions.index.tolist())

print("\nNumber of such positions:", len(different_positions))

Positions containing two different songs:
[8, 10, 11, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48, 49]

Number of such positions: 33

In [35]:
print(
    march_1[
        march_1["position"].isin(different_positions.index)
    ][["position", "song", "artist", "popularity"]]
    .sort_values("position")
    .head(20)
)

       position                                      song  \
14357         8  Young Miko: Bzrp Music Sessions, Vol. 58
14407         8                                  Casanova
14409        10                                 Gata Only
14359        10                                  Casanova
14360        11                                 Gata Only
14410        11  Young Miko: Bzrp Music Sessions, Vol. 58
14412        13                                  El Patio
14362        13                           La_Original.mp3
14363        14                                 LA ÚLTIMA
14413        14                           La_Original.mp3
14414        15                                 LA ÚLTIMA
14364        15                               PERRO NEGRO
14365        16                                  El Patio
14415        16                               PERRO NEGRO
14420        21                                   LA CAPI
14370        21                                  Columbia
14371        22                                   BAD BOY
14421        22                                  Columbia
14422        23                                   BAD BOY
14372        23                                  MODELITO

                                artist  popularity
14357            Bizarrap & Young Miko          94
14407    Soolking & Lola Indigo & Rvfv          82
14409             FloyyMenor & Cris Mj          90
14359    Soolking & Lola Indigo & Rvfv          83
14360             FloyyMenor & Cris Mj          90
14410            Bizarrap & Young Miko          94
14412  Pepe y Vizio & Delaossa & KIDDO          73
14362                           Emilia          85
14363                          Quevedo          84
14413                           Emilia          85
14414                          Quevedo          83
14364                        Bad Bunny          95
14365  Pepe y Vizio & Delaossa & KIDDO          73
14415                        Bad Bunny          95
14420                      Myke Towers          80
14370                          Quevedo          92
14371  Chris Jedi & Gaby Music & Dei V          77
14421                          Quevedo          91
14422  Chris Jedi & Gaby Music & Dei V          77
14372                             Mora          83

In [36]:
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing exact duplicates:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 27800
Rows after removing exact duplicates: 27785
Rows removed: 15

In [37]:
march_1_clean = df_clean[
    df_clean["date"] == "01-03-2025"
].copy()

print("Records on 01-03-2025 after duplicate removal:",
      len(march_1_clean))

print("\nRecords per position:")
print(
    march_1_clean["position"]
    .value_counts()
    .sort_index()
)

Records on 01-03-2025 after duplicate removal: 85

Records per position:
position
1     2
2     1
3     1
4     1
5     1
6     1
7     1
8     2
9     1
10    2
11    2
12    1
13    2
14    2
15    2
16    2
17    1
18    2
19    1
20    1
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    2
33    2
34    2
35    1
36    2
37    2
38    2
39    1
40    1
41    2
42    2
43    2
44    2
45    2
46    2
47    2
48    2
49    2
50    1
Name: count, dtype: int64

In [38]:
march_1_clean[["position", "song", "artist"]].head(20)

,position,song,artist
14350,1,FARDOS,JC Reyes & De La Ghetto
14351,2,Manos Rotas,DELLAFUENTE & Morad
14352,3,LA FALDA,Myke Towers
14353,4,X'CLUSIVO,Gonzy
14354,5,LUNA,Feid
14355,6,M.A.I,Milo j
14356,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK
14357,8,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko
14358,9,Mamichula - con Nicki Nicole,Trueno
14359,10,Casanova,Soolking & Lola Indigo & Rvfv
14360,11,Gata Only,FloyyMenor & Cris Mj
14361,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L
14362,13,La_Original.mp3,Emilia
14363,14,LA ÚLTIMA,Quevedo
14364,15,PERRO NEGRO,Bad Bunny
14365,16,El Patio,Pepe y Vizio & Delaossa & KIDDO
14366,17,UNA BACHATA,Lola Indigo
14367,18,Buscando Money,TWENTY SIX & Tayson Kryss
14368,19,A 300,JC Reyes & Pedro Calderon & Blacknife
14369,20,CONTIGO (with Tiësto),KAROL G & Tiësto

In [39]:
print(
    "First position:",
    march_1_clean.iloc[0]["position"]
)

print(
    "Last position:",
    march_1_clean.iloc[49]["position"]
)

First position: 1
Last position: 50

In [40]:
# Separate the abnormal date from the rest of the dataset
normal_data = df_clean[
    df_clean["date"] != "01-03-2025"
].copy()

# Get the first complete 1–50 snapshot from the abnormal date
march_1_snapshot = (
    march_1_clean
    .iloc[:50]
    .copy()
)

# Combine the cleaned normal data with the retained snapshot
df_clean = pd.concat(
    [normal_data, march_1_snapshot],
    ignore_index=True
)

print("Cleaned dataset shape:", df_clean.shape)

Cleaned dataset shape: (27750, 10)

In [41]:
daily_counts_clean = df_clean.groupby("date").size()

print(
    "Dates with exactly 50 records:",
    (daily_counts_clean == 50).sum()
)

print(
    "Dates with records other than 50:",
    (daily_counts_clean != 50).sum()
)

print("\nAbnormal dates:")
print(daily_counts_clean[daily_counts_clean != 50])

Dates with exactly 50 records: 555
Dates with records other than 50: 0

Abnormal dates:
Series([], dtype: int64)

In [42]:
print("Exact duplicate rows remaining:",
      df_clean.duplicated().sum())

Exact duplicate rows remaining: 0

In [43]:
duplicate_song_date = (
    df_clean.groupby(["date", "song"])
    .size()
    .reset_index(name="count")
)

duplicate_song_date = duplicate_song_date[
    duplicate_song_date["count"] > 1
]

print(
    "Duplicate song-date combinations:",
    len(duplicate_song_date)
)

Duplicate song-date combinations: 12

In [44]:
duplicate_song_date

             date  song  count
227    01-05-2025  LUNA      2
1124   02-05-2025  LUNA      2
2024   03-05-2025  LUNA      2
2924   04-05-2025  LUNA      2
3822   05-05-2025  LUNA      2
4721   06-05-2025  LUNA      2
5620   07-05-2025  LUNA      2
6519   08-05-2025  LUNA      2
7417   09-05-2025  LUNA      2
24769  28-04-2025  LUNA      2
25619  29-04-2025  LUNA      2
26467  30-04-2025  LUNA      2

In [45]:
print("Number of duplicate song-date combinations:",
      len(duplicate_song_date))

print("\nDates containing duplicate songs:")
print(duplicate_song_date["date"].value_counts())

Number of duplicate song-date combinations: 12

Dates containing duplicate songs:
date
01-05-2025    1
02-05-2025    1
03-05-2025    1
04-05-2025    1
05-05-2025    1
06-05-2025    1
07-05-2025    1
08-05-2025    1
09-05-2025    1
28-04-2025    1
29-04-2025    1
30-04-2025    1
Name: count, dtype: int64

In [46]:
duplicate_song_date.head(12)

             date  song  count
227    01-05-2025  LUNA      2
1124   02-05-2025  LUNA      2
2024   03-05-2025  LUNA      2
2924   04-05-2025  LUNA      2
3822   05-05-2025  LUNA      2
4721   06-05-2025  LUNA      2
5620   07-05-2025  LUNA      2
6519   08-05-2025  LUNA      2
7417   09-05-2025  LUNA      2
24769  28-04-2025  LUNA      2
25619  29-04-2025  LUNA      2
26467  30-04-2025  LUNA      2

In [47]:
luna_duplicates = df_clean[
    (df_clean["song"] == "LUNA") &
    (df_clean["date"].isin(
        duplicate_song_date["date"]
    ))
].sort_values(["date", "position"])

luna_duplicates[
    ["date", "position", "song", "artist", "popularity", "album_type"]
]

             date  position  song artist  popularity album_type
17263  01-05-2025        14  LUNA   Feid          93      album
17266  01-05-2025        17  LUNA  SAIKO          67      album
17312  02-05-2025        13  LUNA   Feid          93      album
17319  02-05-2025        20  LUNA  SAIKO          67      album
17363  03-05-2025        14  LUNA   Feid          93      album
17372  03-05-2025        23  LUNA  SAIKO          68      album
17411  04-05-2025        12  LUNA   Feid          93      album
17426  04-05-2025        27  LUNA  SAIKO          69      album
17460  05-05-2025        11  LUNA   Feid          93      album
17486  05-05-2025        37  LUNA  SAIKO          70      album
17508  06-05-2025         9  LUNA   Feid          93      album
17543  06-05-2025        44  LUNA  SAIKO          70      album
17558  07-05-2025         9  LUNA   Feid          93      album
17592  07-05-2025        43  LUNA  SAIKO          70      album
17610  08-05-2025        11  LUNA   Feid          93      album
17637  08-05-2025        38  LUNA  SAIKO          70      album
17660  09-05-2025        11  LUNA   Feid          93      album
17696  09-05-2025        47  LUNA  SAIKO          70      album
17108  28-04-2025         9  LUNA  SAIKO          61      album
17116  28-04-2025        17  LUNA   Feid          94      album
17164  29-04-2025        15  LUNA   Feid          94      album
17167  29-04-2025        18  LUNA  SAIKO          64      album
17213  30-04-2025        14  LUNA   Feid          93      album
17215  30-04-2025        16  LUNA  SAIKO          65      album

In [48]:
print(
    luna_duplicates.groupby("date")["position"]
    .apply(list)
)

date
01-05-2025    [14, 17]
02-05-2025    [13, 20]
03-05-2025    [14, 23]
04-05-2025    [12, 27]
05-05-2025    [11, 37]
06-05-2025     [9, 44]
07-05-2025     [9, 43]
08-05-2025    [11, 38]
09-05-2025    [11, 47]
28-04-2025     [9, 17]
29-04-2025    [15, 18]
30-04-2025    [14, 16]
Name: position, dtype: object

In [49]:
duplicate_songs = (
    df_clean.groupby(["date", "song"])
    .size()
    .reset_index(name="count")
)

duplicate_songs = duplicate_songs[
    duplicate_songs["count"] > 1
]

print("Duplicate song-date cases:", len(duplicate_songs))
print("\nUnique songs involved:")
print(duplicate_songs["song"].unique())

Duplicate song-date cases: 12

Unique songs involved:
<ArrowStringArray>
['LUNA']
Length: 1, dtype: str

In [50]:
print(
    duplicate_songs["song"]
    .value_counts()
)

song
LUNA    12
Name: count, dtype: int64

In [51]:
print("========== FINAL DATA VALIDATION ==========")

print("Total rows:", len(df_clean))
print("Total columns:", len(df_clean.columns))
print("Unique dates:", df_clean["date"].nunique())

daily_counts_final = df_clean.groupby("date").size()

print("\nDates with exactly 50 records:",
      (daily_counts_final == 50).sum())

print("Dates with records other than 50:",
      (daily_counts_final != 50).sum())

print("\nExact duplicate rows:",
      df_clean.duplicated().sum())

print("\nMissing values:")
print(df_clean.isnull().sum())

print("===========================================")

========== FINAL DATA VALIDATION ==========
Total rows: 27750
Total columns: 10
Unique dates: 555

Dates with exactly 50 records: 555
Dates with records other than 50: 0

Exact duplicate rows: 0

Missing values:
date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64
===========================================

In [52]:
df_clean.to_csv(
    "../data/cleaned_data.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [53]:
import os

file_path = "../data/cleaned_data.csv"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print("File size:", round(os.path.getsize(file_path) / 1024, 2), "KB")

File exists: True
File size: 3613.97 KB